CC=g++
SOURCES = main.cpp ../source/Gestor.cc ../source/Cola.cc ../source/Lista.cc ../source/Aficionado.cc ../source/Pila.cc ../source/NodoCola.cc ../source/NodoPila.cc ../source/NodoLista.cc

all: main

main:
	$(CC) $(SOURCES)
